### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by lptrk** [lptrk/Sportverein-Scherg#1]
**Front-End**
- [ ] Login-Seite (Frontend)
- [ ]  Mitgliederverwaltung-Seite (Frontend)
- [ ] Bearbeitungsmodus Tabelle (Frontend)

**Back-End**
- [ ] Login-Seite (Backend)
- [ ] Mitgliederverwaltung-Seite (Backend)
- [ ] Bearbeitungsmodus Tabelle (Backend)

**Drecksarbeit**
- [ ] Dokumentation über die Anwendung(?)
- [ ] UML-Diagramm
- [ ] Gegenseitige Erklärung und Vorbereitung auf das Fachgespräch

**Comment by lptrk** [comment]
**!Wichtig!**
Falls euch noch Sachen einfallen, die gemacht werden müssen schreibt sie bitte in die ToDo-Liste.
(Sollte eigentlich ganz einfach sein; oben auf die 3 Punkte und auf "Edit" gehen.)
Und wenn ein Punkt erledigt ist, diesen auch bitte abhaken. :)
